ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "utm_source" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "utm_medium" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "utm_campaign" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "utm_content" TEXT;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "utm_term" TEXT;
