ALTER TABLE "LessonConfirmation"
ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'DAILY_MESSAGE';

ALTER TABLE "MessageSettings"
ADD COLUMN IF NOT EXISTS "admin_quick_tip_enabled" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "MessageSettings"
ADD COLUMN IF NOT EXISTS "quick_tip_enabled" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "MessageSettings"
ADD COLUMN IF NOT EXISTS "quick_tip_time" VARCHAR(5) NOT NULL DEFAULT '12:00';
